# Generated by Django 4.2.5 on 2023-10-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
    ]
